language: go

go:
  - 1.x

install:
  - go get github.com/golang/lint/golint
  - go get -u github.com/golang/dep/cmd/dep


script:
  - dep ensure
  - go test -race -cover ./

after_script:
  - golint ./
